### PR TITLE
Fix NODE_ENV Strict Mode

### PR DESCRIPTION
**Pull request by jeremywillans**
Create production.json to fix NODE_ENV Strict Mode

### CODE REVIEW

**Comment by jeremywillans** [comment]
Bump @koalazak

**Comment by koalazak** [comment]
thanks!

can you increaste the version string in package.json? to `2.1.2`

thank you

**Comment by jeremywillans** [comment]
done, also bumped dorita980 to latest 3.1.9

**Comment by koalazak** [comment]
ty!

**Pull request merged**
